logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  file: logs/config-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka/

spring:
  profiles:
    active: prod
  application:
    name: config-service
    boot:
      admin:
        client:
          url: http://admin-service:9094/admin
          username: "user"
          password: "password"
  zipkin:
    base-url: http://zipkin-service:9095/